"""
app/models.py - Agent Output Data Contracts & Schemas.

Defines the Pydantic data structures used for single-agent ReAct parsing,
individual tool inputs, and Phase 3.1 Multi-Agent Collaboration protocol handoffs.
"""

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


# -------------------------------------------------------------
# Single-Agent / Specialist Internal Step Schema
# -------------------------------------------------------------
class OutputFormat(BaseModel):
    """
    Data contract enforcing the step structure expected from the LLM
    during internal reasoning and execution.

    Attributes:
        STEP (Literal): Current execution phase ("START", "PLAN", "REFLECT", "EXPLANATION", "TOOL", or "ANSWER").
        CONTENT (str): Human-readable explanation, reflection diagnosis, or summary.
        TOOL (str | None): Name of the tool to invoke (only populated when STEP == "TOOL").
        INPUT (dict[str, Any] | None): Dictionary of arguments to pass to the tool function.
        PLAN_STEPS (list[str] | None): Ordered list of subtasks when formulating a plan.
    """

    STEP: Literal["START", "PLAN", "REFLECT", "EXPLANATION", "TOOL", "ANSWER"]
    CONTENT: str
    TOOL: str | None = None
    INPUT: dict[str, Any] | None = None
    PLAN_STEPS: list[str] | None = None


# -------------------------------------------------------------
# Phase 3.1 Multi-Agent Communication & Delegation Schemas
# -------------------------------------------------------------
class AgentRole(str, Enum):
    """
    Enumeration of all available specialist worker agents in the team.
    """

    SUPERVISOR = "SupervisorAgent"
    RESEARCHER = "ResearchAgent"
    DATA_ANALYST = "DataAnalystAgent"
    DOC_VISION = "DocVisionAgent"


class SubTask(BaseModel):
    """
    Represents an atomic task delegated by the Supervisor to a specialist.
    """

    task_id: int = Field(
        default=..., 
        description="Sequential index identifier for this subtask (e.g., 1, 2, 3).",
    )
    assigned_agent: AgentRole = Field(
        default=..., 
        description="The target worker agent best equipped to handle this task.",
    )
    instruction: str = Field(
        default=...,
        description="Clear, context-contained instruction explaining what the agent must do.",
    )
    dependencies: list[int] = Field(
        default_factory=list,
        description=(
            "Crucial list of integer task_ids that MUST finish before this task runs. "
            "For example, if this task inspects a chart generated by task 1, this MUST be [1]. "
            "Task 1 should have [], but subsequent dependent tasks MUST NEVER leave this empty."
        ),
    )
    expected_output: str = Field(
        default=...,
        description="Brief description of the expected output format or key facts needed.",
    )


class TaskResult(BaseModel):
    """
    Structured outcome returned by a worker agent after finishing an assigned subtask.
    """

    task_id: int
    assigned_agent: str
    status: Literal["BLOCKED", "FAILED", "SKIPPED", "SUCCESS"]
    summary: str = Field(
        default=...,
        description="Concise factual findings, code results, or extracted knowledge.",
    )
    artifacts: list[str] = Field(
        default_factory=list,
        description="List of filenames or resources generated in workspace (e.g., 'chart.png').",
    )
    error_message: str | None = None


class SupervisorDecision(BaseModel):
    """
    Response schema produced by the Supervisor on each orchestration turn.
    """

    ACTION: Literal["DELEGATE", "SYNTHESIZE", "DIRECT_ANSWER"] = Field(
        default=...,
        description=(
            "Action choice: 'DELEGATE' to assign subtasks to specialist workers; "
            "'SYNTHESIZE' to combine completed worker results into the formatted final user answer along with mandatory urls and data; "
            "'DIRECT_ANSWER' for everyday conversational greetings or basic factual queries."
        ),
    )
    REASONING: str = Field(
        default=...,
        description="Supervisor's internal step-by-step logic behind the delegation or synthesis.",
    )
    SUBTASKS: list[SubTask] | None = Field(
        default=None, 
        description="List of subtasks when ACTION is 'DELEGATE'.",
    )
    FINAL_ANSWER: str | None = Field(
        default=None,
        description="Consolidated final user response when ACTION is 'SYNTHESIZE' or 'DIRECT_ANSWER'.",
    )


# =============================================================
# =============================================================
# Tool Input Validation Schemas
# =============================================================
# =============================================================

# -----------------------------------------------
# Pydantic Schema for Code Interpreter Tool Input
# -----------------------------------------------
class CodeInterpreterInput(BaseModel):
    """Pydantic schema validating Python code string inputs generated by LLMs."""

    code: str = Field(
        ...,
        description=(
            "Valid Python code to execute. Standard data science and math tools "
            "(math, numpy, sympy, pandas, matplotlib) are automatically available. "
            "Write code for math, symbolic equations, calculus, data processing, or plotting. "
            "Assign output to `result` or use `print()`. "
            "Files in `./nova_workspace` are accessible directly in current working directory. "
            "Save charts directly to disk using `plt.savefig('chart.png')`."
        ),
    )


# --------------------------------------
# Pydantic Schema for Weather Tool Input
# --------------------------------------
class WeatherInput(BaseModel):
    """Pydantic input schema for weather city parameters."""

    cities: list[str] = Field(
        description="A list of city names to fetch weather for. Correct any typos in city names first."
    )


# -----------------------------------------
# Pydantic Schema for Web Search Tool Input
# -----------------------------------------
class WebSearchInput(BaseModel):
    """Pydantic validation schema for search query strings."""

    query: str = Field(description="The search query string to look up on the web.")
    time_range: Literal["day", "week", "month", "year"] | None = Field(
        default=None,
        description="Optional freshness filter. Use 'day' for breaking news/today's live status, 'week' for recent events, or leave null for general queries.",
    )


# -----------------------------------------
# Pydantic Schema for List Files Tool Input
# -----------------------------------------
class ListFilesInput(BaseModel):
    subfolder: str | None = Field(
        default="",
        description="Optional relative subfolder within workspace (e.g., 'data' or 'reports'). Leave empty for root.",
    )
    pattern: str | None = Field(
        default="*",
        description="Optional glob pattern to filter files, e.g., '*.csv' or '*.json'.",
    )


# ------------------------------------------
# Pydantic Schema for Inspect CSV Tool Input
# ------------------------------------------
class InspectCSVInput(BaseModel):
    file_path: str = Field(
        default=...,
        description="Relative path to the CSV file inside the workspace (e.g., 'sales_2025.csv').",
    )
    sample_rows: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of sample rows to return for preview.",
    )


# ------------------------------------------
# Pydantic Schema for Inspect PDF Tool Input
# ------------------------------------------
class InspectPDFInput(BaseModel):
    file_path: str = Field(
        default=...,
        description="Relative path to the PDF file inside the workspace (e.g., 'sample.pdf').",
    )
    max_pages_to_sample: int = Field(
        default=2,
        ge=1,
        le=5,
        description="Number of sample pages to return for preview",
    )

# ----------------------------------------------------
# Pydantic Schema for Search Knowledge Base Tool Input
# ----------------------------------------------------
class SearchKnowledgeBaseInput(BaseModel):
    query: str = Field(
        default=...,
        description="he natural language search query or concept to look up in workspace documents.",
    )
    n_results: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of relevant chunks to retrieve (default is 3).",
    )

# ----------------------------------------------------
# Pydantic Schema for Inspect Image Tool Input
# ----------------------------------------------------
class InspectImageInput(BaseModel):
    file_path: str = Field(
        default=...,
        description="Relative path to the image to the image file inside workspace (e.g., 'chart.png' or 'diagram.jpg')",
    )
    prompt: str = Field(
        default="Describe this image in detail and extract all key visuals insights, labels and text.",
        description="The specific question, observation request, or analysis prompt to ask about this image",
    )