"""
models.py - Agent Output Data Contracts & Schemas.

Defines the Pydantic data structure used for strict JSON response parsing
from the local LLM.
"""

from typing import Any, Literal

from pydantic import BaseModel, Field


# --------------------------------------
# Pydantic Schema for LLM Output Parsing
# --------------------------------------
class OutputFormat(BaseModel):
    """
    Data contract enforcing the ReAct protocol step structure expected
    from the LLM's JSON response.

    Attributes:
        STEP (Literal): Current execution phase ("START", "EXPLANATION", "TOOL", or "ANSWER").
        CONTENT (str): Human-readable explanation or summary of the current step.
        TOOL (str | None): Name of the tool to invoke (only populated when STEP == "TOOL").
        INPUT (dict[str, Any] | None): Dictionary of arguments to pass to the tool function.
    """

    STEP: Literal["START", "EXPLANATION", "TOOL", "ANSWER"]
    CONTENT: str
    TOOL: str | None = None
    INPUT: dict[str, Any] | None = None


# -----------------------------------------------
# Pydantic Schema for Code Interpreter Tool Input
# -----------------------------------------------
class CodeInterpreterInput(BaseModel):
    """Pydantic schema validating Python code string inputs generated by LLMs."""

    code: str = Field(
        ...,
        description=(
            "Valid Python code to execute. Standard data science and math tools "
            "(math, numpy, sympy, pandas, matplotlib) are automatically available. "
            "Write code for math, symbolic equations, calculus, data processing, or plotting. "
            "Assign output to `result` or use `print()`. "
            "Files in `./nova_workspace` are accessible directly in current working directory. "
            "Save charts directly to disk using `plt.savefig('chart.png')`."
        ),
    )


# --------------------------------------
# Pydantic Schema for Weather Tool Input
# --------------------------------------
class WeatherInput(BaseModel):
    """Pydantic input schema for weather city parameters."""

    cities: list[str] = Field(
        description="A list of city names to fetch weather for. Correct any typos in city names first."
    )


# -----------------------------------------
# Pydantic Schema for Web Search Tool Input
# -----------------------------------------
class WebSearchInput(BaseModel):
    """Pydantic validation schema for search query strings."""

    query: str = Field(
        description="Concise search query optimized for real-time search engine retrieval (e.g., 'Nifty 50 today stock price' or 'The Hundred 2026 cricket schedule')."
    )


# -----------------------------------------
# Pydantic Schema for List Files Tool Input
# -----------------------------------------
class ListFilesInput(BaseModel):
    subfolder: str | None = Field(
        default="",
        description="Optional relative subfolder within workspace (e.g., 'data' or 'reports'). Leave empty for root.",
    )
    pattern: str | None = Field(
        default="*",
        description="Optional glob pattern to filter files, e.g., '*.csv' or '*.json'.",
    )


# ------------------------------------------
# Pydantic Schema for Inspect CSV Tool Input
# ------------------------------------------
class InspectCSVInput(BaseModel):
    file_path: str = Field(
        default=...,
        description="Relative path to the CSV file inside the workspace (e.g., 'sales_2025.csv').",
    )
    sample_rows: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of sample rows to return for preview.",
    )


# ------------------------------------------
# Pydantic Schema for Inspect PDF Tool Input
# ------------------------------------------
class InspectPDFInput(BaseModel):
    file_path: str = Field(
        default=...,
        description="Relative path to the PDF file inside the workspace (e.g., 'sample.pdf').",
    )
    max_pages_to_sample: int = Field(
        default=2,
        ge=1,
        le=5,
        description="Number of sample pages to return for preview",
    )