"""
code_interpreter.py - Secure Python Execution Sandbox Engine.
Evaluates Python code safely for calculations, math equations, plotting, and data analysis.
"""

import contextlib
import io
import math
import traceback

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sympy
from pydantic import BaseModel, Field

# Force headless rendering backend for matplotlib (prevents GUI display crashes)
matplotlib.use("Agg")


class CodeInterpreterInput(BaseModel):
    """Pydantic schema validating Python code string inputs generated by LLMs."""

    code: str = Field(
        description=(
            "Valid Python code to execute. Write code for math, symbolic equations, "
            "data processing, or plotting with matplotlib. Assign output to `result` or `print()`."
        )
    )


BLOCKED_MODULES = {
    "os",
    "sys",
    "subprocess",
    "shutil",
    "pathlib",
    "builtins",
    "socket",
    "requests",
}


def safe_import(name, globals=None, locals=None, fromlist=(), level=0):
    """Custom import hook restricting access to sensitive operating system modules."""
    root_module = name.split(".")[0]
    if root_module in BLOCKED_MODULES:
        raise ImportError(
            f"Importing '{root_module}' is restricted for security reasons."
        )
    return __import__(name, globals, locals, fromlist, level)


class CodeInterpreter:
    """Sandbox execution wrapper using math, numpy, sympy, pandas, and matplotlib."""

    @staticmethod
    def run_python_code(code: str) -> dict:
        stdout_buffer = io.StringIO()

        safe_globals = {
            "__builtins__": {
                "abs": abs,
                "min": min,
                "max": max,
                "sum": sum,
                "len": len,
                "range": range,
                "list": list,
                "dict": dict,
                "float": float,
                "int": int,
                "str": str,
                "print": print,
                "isinstance": isinstance,
                "enumerate": enumerate,
                "zip": zip,
                "__import__": safe_import,
            },
            # Scientific & Data Libraries
            "math": math,
            "sympy": sympy,
            "sp": sympy,
            "numpy": np,
            "np": np,
            "pandas": pd,
            "pd": pd,
            "plt": plt,
            "matplotlib": matplotlib,
            # Common Math Functions
            "sqrt": math.sqrt,
            "sin": math.sin,
            "cos": math.cos,
            "tan": math.tan,
            "log": math.log,
            "exp": math.exp,
            "pi": math.pi,
            "e": math.e,
            # SymPy Algebraic Shortcuts
            "Symbol": sympy.Symbol,
            "Symbols": sympy.symbols,
            "Eq": sympy.Eq,
            "solve": sympy.solve,
            "diff": sympy.diff,
            "integrate": sympy.integrate,
            "Matrix": sympy.Matrix,
        }
        safe_locals = {}

        try:
            with contextlib.redirect_stdout(stdout_buffer):
                exec(code, safe_globals, safe_locals)  # noqa: S102

            output = stdout_buffer.getvalue().strip()
            result_val = safe_locals.get("result", None)

            if not output and result_val is not None:
                output = str(result_val)

            return {
                "success": True,
                "output": output,
                "result_variable": str(result_val) if result_val is not None else None,
            }
        except Exception as e:  # noqa: BLE001
            error_msg = traceback.format_exc()
            print(f"\n[CodeInterpreter Exec Error]: {e}\n")
            return {"success": False, "error": str(e), "traceback": error_msg}
