"""
code_interpreter.py - Secure Python Execution Sandbox Engine.

Enables NovaAI to write and execute Python code safely for mathematical,
symbolic, and data processing tasks.
"""

import contextlib
import io
import math
import traceback

import numpy as np
import sympy
from pydantic import BaseModel, Field


class CodeInterpreterInput(BaseModel):
    """Pydantic schema validating Python code string inputs generated by LLMs."""

    code: str = Field(
        description="Valid Python code to execute. Write code for math calculations, symbolic math, or data processing. " \
                    "Assign the answer to a variable named `result` or use `print()`."
    )


# Standard library modules blocked from import for sandbox execution security
BLOCKED_MODULES = {
    "os",
    "sys",
    "subprocess",
    "shutil",
    "pathlib",
    "builtins",
    "socket",
    "requests",
}


def safe_import(name, globals=None, locals=None, fromlist=(), level=0):
    """Custom import hook preventing restricted system modules from being imported inside sandbox."""
    root_module = name.split(".")[0]
    if root_module in BLOCKED_MODULES:
        raise ImportError(
            f"Importing '{root_module}' is restricted for security reasons."
        )
    return __import__(name, globals, locals, fromlist, level)


class CodeInterpreter:
    """Sandbox execution wrapper for isolated Python evaluation using math, numpy, and sympy."""

    @staticmethod
    def run_python_code(code: str) -> dict:
        """
        Executes raw Python code string inside a restricted global namespace.

        Args:
            code (str): Python source code to evaluate.

        Returns:
            dict: Execution status, captured STDOUT output, and variable results.
        """
        stdout_buffer = io.StringIO()

        # Define safe builtins and mathematical namespaces
        safe_globals = {
            "__builtins__": {
                "abs": abs,
                "min": min,
                "max": max,
                "sum": sum,
                "len": len,
                "range": range,
                "list": list,
                "dict": dict,
                "float": float,
                "int": int,
                "str": str,
                "print": print,
                "isinstance": isinstance,
                "enumerate": enumerate,
                "zip": zip,
                "__import__": safe_import,
            },
            # Scientific & Mathematical Libraries
            "math": math,
            "sympy": sympy,
            "sp": sympy,
            "numpy": np,
            "np": np,
            # Math Function Shortcuts
            "sqrt": math.sqrt,
            "sin": math.sin,
            "cos": math.cos,
            "tan": math.tan,
            "log": math.log,
            "log10": math.log10,
            "log2": math.log2,
            "exp": math.exp,
            "pi": math.pi,
            "e": math.e,
            # SymPy Algebraic Methods
            "Symbol": sympy.Symbol,
            "Symbols": sympy.symbols,
            "Eq": sympy.Eq,
            "solve": sympy.solve,
            "diff": sympy.diff,
            "integrate": sympy.integrate,
            "limit": sympy.limit,
            "Matrix": sympy.Matrix,
            "factor": sympy.factor,
        }
        safe_locals = {}

        try:
            # Redirect standard output stream to capture print statements
            with contextlib.redirect_stdout(stdout_buffer):
                exec(code, safe_globals, safe_locals)  # noqa: S102

            output = stdout_buffer.getvalue().strip()
            result_val = safe_locals.get("result", None)

            # Fallback to 'result' variable string if print was omitted
            if not output and result_val is not None:
                output = str(result_val)

            return {
                "success": True,
                "output": output,
                "result_variable": str(result_val) if result_val is not None else None,
            }
        except Exception as e:  # noqa: BLE001
            error_msg = traceback.format_exc()
            print(f"\n[CodeInterpreter Exec Error]: {e}\n")
            return {"success": False, "error": str(e), "traceback": error_msg}
