"""
code_interpreter.py - Hybrid Python Execution Sandbox Engine.

Dual-mode execution engine for NovaAI:
1. Docker Mode (Primary): Executes code inside a restricted, isolated Docker container.
2. Local Mode (Fallback): Executes code locally if Docker Desktop is closed or missing.
"""

# import contextlib
# import io
# import math
import os
import sys

# import traceback
from pathlib import Path

import docker
from docker.errors import ContainerError, DockerException
from pydantic import BaseModel, Field

# ------------------------------------------------------------------
# Self-healing import path setup: Ensures Python can find 'app.core'
# regardless of where or how this script is executed from terminal.
# ------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.core.workspace_manager import workspace

# ------------------------------------------------------------------
# Soft Docker Check: Prevents app crash if the `docker` python SDK
# isn't installed on the developer's machine.
# ------------------------------------------------------------------
try:
    import docker

    DOCKER_AVAILABLE = True
except ImportError:
    DOCKER_AVAILABLE = False


# ------------------------------------------------------------------
# Pydantic Schema: Communicates input rules & requirements to LLM
# ------------------------------------------------------------------
class CodeInterpreterInput(BaseModel):
    """Pydantic schema validating Python code string inputs generated by LLMs."""

    code: str = Field(
        ...,
        description=(
            "Valid Python code to execute. Standard data science and math tools "
            "(math, numpy, sympy, pandas, matplotlib) are automatically available. "
            "Write code for math, symbolic equations, calculus, data processing, or plotting. "
            "Assign output to `result` or use `print()`. "
            "Files in `./nova_workspace` are accessible directly in current working directory. "
            "Save charts directly to disk using `plt.savefig('chart.png')`."
        ),
    )


class CodeInterpreter:
    """Sandbox execution wrapper with Docker support and local fallback."""

    # --------------------------------------------------------------
    # MODE 1: Main Execution Router (Docker -> Local Fallback)
    # --------------------------------------------------------------
    @staticmethod
    def run_python_code(
        params: CodeInterpreterInput | None = None,
        code: str | None = None,
    ):
        """Runs Python code using Docker if running, otherwise falls back to local execution."""
        # Convert raw keyword arg 'code' into CodeInterpreterInput if passed directly by agent.py
        if params is None:
            if code is None:
                return {
                    "success": False,
                    "output": None,
                    "error": "No Python code provided to execute.",
                }
            params = CodeInterpreterInput(code=code)

        # ----------------------------------------------------------
        # PREAMBLE WRAPPER:
        # Automatically imports common libraries so NovaAI doesn't
        # have to write boilerplate import statements every turn.
        # ----------------------------------------------------------
        wrapped_code = (
            "import math, sys\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib\n"
            "matplotlib.use('Agg')\n"  # Headless backend: stops popup GUI windows from crashing headless containers
            "import matplotlib.pyplot as plt\n"
            "try:\n"
            "    import sympy as sp\n"
            "    from sympy import Symbol, symbols, Eq, solve, diff, integrate, Matrix, sqrt, sin, cos, tan, log, exp, pi, oo\n"
            "except ImportError:\n"
            "    pass\n\n"
            "# --- LLM Generated Code Execution ---\n"
            f"{params.code}\n\n"
            "# Auto-print result variable if defined\n"
            "if 'result' in locals() and result is not None:\n"
            "    print(result)\n"
        )

        # ----------------------------------------------------------
        # STEP 1: Attempt Isolated Docker Execution
        # ----------------------------------------------------------
        if DOCKER_AVAILABLE:
            try:
                client = docker.from_env()

                # Check if Docker Desktop / Daemon is actually active and responsive
                client.ping()

                # Dynamic path resolution for Docker-out-of-Docker
                host_project_env = os.getenv("HOST_PROJECT_PATH")
                if host_project_env:
                    host_workspace_path = str(Path(host_project_env) / "nova_workspace")
                else:
                    host_workspace_path = str(workspace.workspace_dir.resolve())

                # Launch ephemeral sandbox container
                output_bytes = client.containers.run(
                    image="nova-sandbox:latest",
                    command=["python", "-c", wrapped_code],
                    volumes={
                        host_workspace_path: {
                            "bind": "/workspace",  # Mount host ./nova_workspace to /workspace
                            "mode": "rw",  # Read-Write permissions
                        }
                    },
                    working_dir="/workspace",  # Run directly inside mounted directory
                    detach=False,
                    remove=True,  # Self-destruct container after execution finishes
                    network_disabled=True,  # SECURITY: Cut off internet access inside sandbox
                    mem_limit="512m",  # SECURITY: Cap RAM usage to prevent system freeze
                    cpu_quota=50000,  # SECURITY: Restrict CPU quota (~50% of 1 core)
                )

                execution_output = output_bytes.decode("utf-8").strip()
                return {
                    "success": True,
                    "output": execution_output
                    if execution_output
                    else "Code executed successfully with no printed output.",
                    "error": None,
                }
            except ContainerError as ce:
                stderr_msg = ce.stderr.decode("utf-8") if ce.stderr else str(ce)  # type: ignore
                return {
                    "success": False,
                    "output": None,
                    "error": f"Execution Runtime Error:\n{stderr_msg}",
                }
            except DockerException as de:
                return {
                    "success": False,
                    "output": None,
                    "error": f"Docker Engine Error. Ensure Docker Desktop is running: {str(de)}",  # noqa: RUF010
                }
            except Exception as e:  # noqa: BLE001
                return {
                    "success": False,
                    "output": None,
                    "error": f"Unexpected CodeInterpreter Error: {str(e)}",  # noqa: RUF010
                }
        # ----------------------------------------------------------
        # Safety Return if Docker SDK is not installed on host
        # ----------------------------------------------------------
        return {
            "success": False,
            "output": None,
            "error": "Docker SDK is not installed or unavailable on this system.",
        }

    # # --------------------------------------------------------------
    # # MODE 2: Local Fallback Execution Engine
    # # Used when Docker is turned off or unavailable on host.
    # # --------------------------------------------------------------
    # @staticmethod
    # def _run_local(code: str) -> dict:
    #     """Fallback local execution engine when Docker is unavailable."""

    #     # Memory buffer to catch anything printed via `print(...)`
    #     stdout_buffer = io.StringIO()

    #     # Build a safe global namespace pre-populated with data science & math tools
    #     safe_globals = {
    #         "__builtins__": __builtins__,
    #         "math": math,
    #         "numpy": sys.modules.get("numpy"),
    #         "np": sys.modules.get("numpy"),
    #         "pandas": sys.modules.get("pandas"),
    #         "pd": sys.modules.get("pandas"),
    #         "plt": sys.modules.get("matplotlib.pyplot"),
    #     }

    #     # Safely attempt pre-loading SymPy for symbolic algebra/calculus
    #     try:
    #         import sympy as sp

    #         safe_globals["sympy"] = sp
    #         safe_globals["sp"] = sp
    #         safe_globals["Symbol"] = sp.Symbol
    #         safe_globals["symbols"] = sp.symbols
    #         safe_globals["Eq"] = sp.Eq
    #         safe_globals["solve"] = sp.solve
    #         safe_globals["diff"] = sp.diff
    #         safe_globals["integrate"] = sp.integrate
    #         safe_globals["Matrix"] = sp.Matrix
    #         safe_globals["sqrt"] = sp.sqrt
    #     except ImportError:
    #         # Fall back to standard math.sqrt if SymPy isn't installed locally
    #         safe_globals["sqrt"] = math.sqrt

    #     safe_locals = {}

    #     try:
    #         # --- DIRECTORY SWAP TRICK ---
    #         # Jump into ./nova_workspace so LLM scripts reading/writing relative
    #         # paths (like 'sales.csv') hit the right directory automatically.
    #         original_dir = Path.cwd()
    #         import os

    #         os.chdir(workspace.workspace_dir)

    #         try:
    #             # Capture standard output stream while code executes
    #             with contextlib.redirect_stdout(stdout_buffer):
    #                 exec(code, safe_globals, safe_locals)
    #         finally:
    #             # CRITICAL: Always jump back to original project root after execution!
    #             os.chdir(original_dir)

    #         # Retrieve printed text and check for auto-assigned `result` variable
    #         output = stdout_buffer.getvalue().strip()
    #         result_val = safe_locals.get("result", None)

    #         # If nothing was printed, auto-print `result` variable if present
    #         if not output and result_val is not None:
    #             output = str(result_val)

    #         return {
    #             "success": True,
    #             "output": output
    #             if output
    #             else "Code executed successfully with no printed output.",
    #             "error": None,
    #         }
    #     except Exception as e:
    #         # Catch runtime errors and format traceback nicely for LLM self-correction
    #         error_msg = traceback.format_exc()
    #         return {
    #             "success": False,
    #             "output": None,
    #             "error": f"Local Execution Error: {str(e)}\n\n{error_msg}",
    #         }


        # ----------------------------------------------------------
        # STEP 2: Graceful Local Fallback
        # Triggers seamlessly if Docker isn't running.
        # ----------------------------------------------------------
        # return CodeInterpreter._run_local(wrapped_code)
